export const dishes = [
    {
        name:"Spaghetti Alla Nerano",
        image:"../assets/Nerano.jpg",
        description:"This classic dish from the Amalfi coast", 
        price: 12,
        availability: true,
        ingredients:" Spaghetti, garlic, olive oil, zucchini, Provolone del Monaco,basil leaves",
    },
    {
        name:"The Lemon Temptress",
        image:"../assets/lemon.webp",
        description:"When life gives you lemons, order lemon spaghetti", 
        price: 9,
        availability:true,
        ingredients:"Linguine, milk, lemons, garlic, olive oil, parsley",
    },
    {
        name:"The Siren’s Enchantment",
        image:"../assets/gnocchi.jpg",
        description:"Try our homemade gnocchi", 
        price: 11,
        availability: true,
        ingredients:"Potatoes, flour, eggs, olive oil, fresh greens, tomatoes",
    },
    {
        name:"Cantuccini",
        image:"../assets/cantuccini.webp",
        description:"You Say Biscotti, I say Cantuccini", 
        price: 8,
        availability: false,
        ingredients:"",
    },
    {
        name:"Zucchini Ensemble",
        image:"../assets/Lasagna.jpg",
        description:"Set this dish aside for the next time you want to impress you ", 
        price: 14,
        availability:true,
        ingredients:"Zuccini, beef, pasta sauce, ricotta, parmesan regianno, mozarella, eggs",
    },
    {
        name:"The Rise of Venus!",
        image:"../assets/mare.jpg",
        description:"There is something about this combination", 
        price: 15,
        availability: true,
        ingredients:"Clams and mussels, shrimps, squid tentacles, olive oil, garlic, white wine, basil, arrabiata sauce, linguine",
    }
];